general:
  general:
    backend: default
    imshow_origin: upper
    zoom_around_mask: true
    disable_zoom_for_fits: true           # If True, the zoom-in around the masked region is disabled when outputting .fits files, which is useful to retain the same dimensions as the input data.
  include_2d:
    border: false
    mapper_image_plane_mesh_grid: false
    mapper_source_plane_data_grid: false
    mapper_source_plane_mesh_grid: false
    mask: true
    origin: true
    parallel_overscan: true
    serial_overscan: true
    serial_prescan: true
  subplot_shape:
    1: (1, 1)                         # The shape of subplots for a figure with 1 subplot.
    2: (2, 2)                         # The shape of subplots for a figure with 2 subplots.
    4: (2, 2)                         # The shape of subplots for a figure with 4 (or less than the above value) of subplots.
    6: (2, 3)                         # The shape of subplots for a figure with 6 (or less than the above value) of subplots.
    9: (3, 3)                         # The shape of subplots for a figure with 9 (or less than the above value) of subplots.
    12: (3, 4)                        # The shape of subplots for a figure with 12 (or less than the above value) of subplots.
    16: (4, 4)                        # The shape of subplots for a figure with 16 (or less than the above value) of subplots.
    20: (4, 5)                        # The shape of subplots for a figure with 20 (or less than the above value) of subplots.
    36: (6, 6)                        # The shape of subplots for a figure with 36 (or less than the above value) of subplots.
    49: (7, 7)                        # The shape of subplots for a figure with 49 (or less than the above value) of subplots.
    64: (8, 8)                        # The shape of subplots for a figure with 64 (or less than the above value) of subplots.
    81: (9, 9)                        # The shape of subplots for a figure with 81 (or less than the above value) of subplots.
    100: (10, 10)                     # The shape of subplots for a figure with 100 (or less than the above value) of subplots.
include:
  include_1d:
    mask: false
    origin: false
  include_2d:
    border: false
    mapper_image_plane_mesh_grid: false
    mapper_source_plane_data_grid: false
    mapper_source_plane_mesh_grid: false
    mask: true
    origin: true
    parallel_overscan: true
    positions: true
    serial_overscan: false
    serial_prescan: true
mat_wrap:
  Axis:
    figure:
      emit: true
    subplot:
      emit: false
  Cmap:
    figure:
      cmap: default
      linscale: 2.0
      linthresh: 1.0
      norm: linear
      vmax: null
      vmin: null
    subplot:
      cmap: default
      linscale: 2.0
      linthresh: 1.0
      norm: linear
      vmax: null
      vmin: null
  Colorbar:
    figure:
      fraction: 3.0
      pad: 4.0
    subplot:
      fraction: 0.1
      pad: 0.2
  ColorbarTickParams:
    figure:
      labelsize: 1
    subplot:
      labelsize: 1
  Figure:
    figure:
      aspect: square
      figsize: (7,7)
    subplot:
      aspect: square
      figsize: auto
  Legend:
    figure:
      fontsize: 12
      include: true
    subplot:
      fontsize: 13
      include: false
  Text:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
  TickParams:
    figure:
      labelsize: 16
    subplot:
      labelsize: 10
  Title:
    figure:
      fontsize: 11
    subplot:
      fontsize: 15
  XLabel:
    figure:
      fontsize: 3
    subplot:
      fontsize: 4
  XTicks:
    figure:
      fontsize: 17
    subplot:
      fontsize: 11
  YLabel:
    figure:
      fontsize: 1
    subplot:
      fontsize: 2
  YTicks:
    figure:
      fontsize: 16
    subplot:
      fontsize: 10
mat_wrap_1d:
  AXVLine:
    figure:
      c: k
      ymin: 0.5
    subplot:
      c: k
      ymin: 0.6
  FillBetween:
    figure:
      alpha: 0.6
      color: k
    subplot:
      alpha: 0.5
      color: k
  YXPlot:
    figure:
      c: k
      linestyle: '-'
      linewidth: 3
    subplot:
      c: k
      linestyle: '-'
      linewidth: 1
  YXScatter:
    figure:
      c: k
      marker: .
    subplot:
      c: k
      marker: x
mat_wrap_2d:
  ArrayOverlay:
    figure:
      alpha: 0.5
    subplot:
      alpha: 0.7
  BorderScatter:
    figure:
      c: c
      marker: +
      s: 13
    subplot:
      c: k
      marker: .
      s: 7
  GridErrorbar:
    figure:
      c: k
      marker: o
    subplot:
      c: b
      marker: .
  GridPlot:
    figure:
      c: k
      linestyle: '-'
      linewidth: 3
    subplot:
      c: k
      linestyle: '-'
      linewidth: 1
  GridScatter:
    figure:
      c: y
      marker: x
      s: 14
    subplot:
      c: r
      marker: .
      s: 6
  IndexScatter:
    figure:
      c: r,g,b,y,k,w
      marker: .
      s: 20
    subplot:
      c: r,g,b,y,w,k
      marker: +
      s: 21
  MaskScatter:
    figure:
      c: g
      marker: .
      s: 12
    subplot:
      c: w
      marker: .
      s: 8
  MeshGridScatter:
    figure:
      c: r
      marker: .
      s: 5
    subplot:
      c: g
      marker: o
      s: 6
  OriginScatter:
    figure:
      c: k
      marker: x
      s: 80
    subplot:
      c: r
      marker: .
      s: 81
  ParallelOverscanPlot:
    figure:
      c: k
      linestyle: '-'
      linewidth: 1
    subplot:
      c: k
      linestyle: '-'
      linewidth: 1
  PatchOverlay:
    figure:
      edgecolor: c
      facecolor: null
    subplot:
      edgecolor: y
      facecolor: null
  PositionsScatter:
    figure:
      c: r,g,b
      marker: o
      s: 15
    subplot:
      c: c,g,b
      marker: .
      s: 5
  SerialOverscanPlot:
    figure:
      c: k
      linestyle: '-'
      linewidth: 2
    subplot:
      c: k
      linestyle: '-'
      linewidth: 1
  SerialPrescanPlot:
    figure:
      c: k
      linestyle: '-'
      linewidth: 3
    subplot:
      c: k
      linestyle: '-'
      linewidth: 1
  VectorYXQuiver:
    figure:
      alpha: 1.0
      angles: xy
      headlength: 0
      headwidth: 1
      linewidth: 5
      pivot: middle
      units: xy
    subplot:
      alpha: 1.1
      angles: xy1
      headlength: 0.1
      headwidth: 11
      linewidth: 51
      pivot: middle1
      units: xy1
  VoronoiDrawer:
    figure:
      alpha: 0.7
      edgecolor: k
      linewidth: 0.3
    subplot:
      alpha: 0.5
      edgecolor: r
      linewidth: 1.0
